### ISSUE TITLE
PESM moo example issue

### ISSUE THREAD

**Issue by martinsimon88** [HIPS/Spearmint#110]
Hello!

I am running PESM on Ubuntu 16.04 and am running into an error and can't get past it:

`Status: 1 pending, 1 complete.
ID(s) of pending job(s) for branin_1, branin_2: 2
Waiting for results...

Fitting GP to 2 data for branin_1 task...
Fitting GP to 2 data for branin_2 task...

Solving Multi-objective global optimization of posterior means!
Traceback (most recent call last):
  File "main.py", line 537, in <module>
    main()
  File "main.py", line 359, in main
    recommendation = chooser.best()
  File "/usr/local/lib/python2.7/dist-packages/spearmint-0.1-py2.7-linux-x86_64.egg/spearmint/choosers/default_chooser.py", line 991, in best
    result_o = moop.get_non_dominated_observations()
  File "/usr/local/lib/python2.7/dist-packages/spearmint-0.1-py2.7-linux-x86_64.egg/spearmint/utils/moop.py", line 302, in get_non_dominated_observations
    if values_final == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

**Comment by danielhernandezlobato** [comment]
In my case it works fine. If it is a problem in your case you may try to change the comparison to "values_final is None" in line 302 of the file spearmint/utils/moop.py
