### ISSUE TITLE
Cannot import gp and util while running 

### ISSUE THREAD

**Issue by mrcavam** [HIPS/Spearmint#112]
Running this 

./spearmint ../examples/braninpy/config.pb --driver=local --method=GPEIOptChooser --method-args=noiseless=1

OR 

python main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 ../examples/braninpy/config.pb

> Gives the following error, how to solve this?
> experiment dir: /home/thsim9/code/spearmint-master/spearmint/examples/braninpy
> Traceback (most recent call last):
>   File "/home/thsim9/code/spearmint-master/spearmint/bin/../spearmint/main.py", line 329, in <module>
>     main()
>   File "/home/thsim9/code/spearmint-master/spearmint/bin/../spearmint/main.py", line 164, in main
>     module  = importlib.import_module('chooser.' + options.chooser_module)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/home/thsim9/code/spearmint-master/spearmint/spearmint/chooser/GPEIOptChooser.py", line 23, in <module>
>     from spearmint import gp
> ImportError: cannot import name gp

**Comment by Shenxiaoqian** [comment]
hello, I've encountered the same problem as you. Have you already resolved it？
