### ISSUE TITLE
NaN crash

### ISSUE THREAD

**Issue by mylesnovick** [HIPS/Spearmint#19]
After several successful runs, it seems spearmint crashes with the following output:
```
/Users/name/Desktop/external_libraries/Spearmint/spearmint/tasks/task.py:287: RuntimeWarning: invalid value encountered in subtract
  return y - mean
Fitting GP for main task...
Traceback (most recent call last):
 File "main.py", line 494, in <module>
   main()
 File "main.py", line 286, in main
   suggested_job = get_suggestion(chooser, resource.tasks, db, expt_dir, options, resource_name)
 File "main.py", line 355, in get_suggestion
   hypers = chooser.fit(task_group, hypers, task_options)
 File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/choosers/default_chooser.py", line 309, in fit
   hypers=hypers.get(task_name, None)
 File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/models/gp.py", line 505, in fit
   self._hypers_list = self._collect_samples(self.mcmc_iters)
 File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/models/gp.py", line 378, in _collect_samples
   sampler.sample(self)
 File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/sampling/slice_sampler.py", line 262, in sample
   params_array, current_ll = slice_sample(params_array, self.logprob, model, **self.sampler_options)
 File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/sampling/mcmc.py", line 354, in slice_sample
   new_x, new_llh = direction_slice(direction, init_x)
 File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/sampling/mcmc.py", line 289, in direction_slice
   llh_s = np.log(npr.rand()) + dir_logprob(0.0)
 File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/sampling/mcmc.py", line 272, in dir_logprob
   return logprob(direction*z + init_x, *logprob_args)
 File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/sampling/slice_sampler.py", line 240, in logprob
   lp += model.log_likelihood()
 File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/models/gp.py", line 538, in log_likelihood
   solve = spla.cho_solve((chol, True), self.observed_values - self.mean.value)
 File "/usr/local/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 162, in cho_solve
   b1 = asarray_chkfinite(b)
 File "/usr/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 613, in asarray_chkfinite
   "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```
---------------

My config file is as follows, if helpful:
```json
{
   "language": "PYTHON",
   "main-file": "stub_optimizing.py",
   "experiment-name": "swingy-monkey-optimization",
   "likelihood": "GAUSSIAN",
   "variables": {
       "height_bucket_div": {
           "type": "FLOAT",
           "size": 1,
           "min": 1,
           "max": 15
       },
       "width_bucket_div": {
           "type": "FLOAT",
           "size": 1,
           "min": 1,
           "max": 10
       },
       "vel_bucket_len": {
           "type": "FLOAT",
           "size": 1,
           "min": 1,
           "max": 30
       },
       "discount": {
           "type": "FLOAT",
           "size": 1,
           "min": 0,
           "max": 1
       },
       "greed_exp": {
           "type": "FLOAT",
           "size": 1,
           "min": 1,
           "max": 3
       }
   }
}
```

**Comment by JasperSnoek** [comment]
Hi @mylesnovick, looks like some numerical instability in the Gaussian
process code.  Could you possibly share your observed inputs and values?
My guess is that the observations are very noisy or oddly behaved, which
makes modeling quite difficult.

**Comment by mylesnovick** [comment]
```
Using database at localhost.
Getting suggestion...

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.000000
                vel_bucket_l  float      1.000000
                width_bucket  float      1.000000
                height_bucke  float      1.000000
Submitted job 1 with local scheduler (process id: 38454).
Status: 1 pending, 0 complete.

Getting suggestion...

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.500000
                vel_bucket_l  float      15.500000
                width_bucket  float      5.500000
                height_bucke  float      8.000000
Submitted job 2 with local scheduler (process id: 38461).
Status: 1 pending, 1 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.55830 (+/- 0.21668), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.492920
                vel_bucket_l  float      15.606201
                width_bucket  float      8.499268
                height_bucke  float      10.799316

Minimum of observed values is 0.600000, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.500000
                vel_bucket_l  float      15.500000
                width_bucket  float      5.500000
                height_bucke  float      8.000000

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490
Submitted job 3 with local scheduler (process id: 38468).
Status: 1 pending, 2 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.01744 (+/- 0.00086), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490

Minimum of observed values is 0.017442, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.999157
                vel_bucket_l  float      29.968313
                width_bucket  float      9.753354
                height_bucke  float      15.000000
Submitted job 4 with local scheduler (process id: 38499).
Status: 1 pending, 3 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.01744 (+/- 0.00083), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490

Minimum of observed values is 0.017442, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490
/Users/name/Desktop/external_libraries/Spearmint/spearmint/transformations/beta_warp.py:206: UserWarning: BetaWarp encountered negative values: [ -1.11022302e-16]
  warnings.warn('BetaWarp encountered negative values: %s' % inputs[inputs<0])
/Users/name/Desktop/external_libraries/Spearmint/spearmint/transformations/beta_warp.py:206: UserWarning: BetaWarp encountered negative values: [ -2.77555756e-17]
  warnings.warn('BetaWarp encountered negative values: %s' % inputs[inputs<0])
/Users/name/Desktop/external_libraries/Spearmint/spearmint/transformations/beta_warp.py:206: UserWarning: BetaWarp encountered negative values: [ -1.11022302e-16  -1.11022302e-16  -2.77555756e-17]
  warnings.warn('BetaWarp encountered negative values: %s' % inputs[inputs<0])

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.825223
                vel_bucket_l  float      20.096509
                width_bucket  float      9.953394
                height_bucke  float      1.000000
Submitted job 5 with local scheduler (process id: 38506).
Status: 1 pending, 4 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.01744 (+/- 0.00079), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490

Minimum of observed values is 0.017442, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      1.075082
                width_bucket  float      10.000000
                height_bucke  float      11.797219
Submitted job 6 with local scheduler (process id: 38513).
Status: 1 pending, 5 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.01745 (+/- 0.00072), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490

Minimum of observed values is 0.017442, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.000000
                vel_bucket_l  float      18.890624
                width_bucket  float      10.000000
                height_bucke  float      15.000000
Submitted job 7 with local scheduler (process id: 38520).
Status: 1 pending, 6 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is -0.02247 (+/- 0.18498), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.949829
                vel_bucket_l  float      11.340454
                width_bucket  float      7.869751
                height_bucke  float      14.885498

Minimum of observed values is 0.017442, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.604825
                vel_bucket_l  float      1.000000
                width_bucket  float      1.000000
                height_bucke  float      14.944403
Submitted job 8 with local scheduler (process id: 38527).
Status: 1 pending, 7 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.01745 (+/- 0.00125), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490

Minimum of observed values is 0.017442, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490
/Users/name/Desktop/external_libraries/Spearmint/spearmint/transformations/beta_warp.py:206: UserWarning: BetaWarp encountered negative values: [ -1.73472348e-18]
  warnings.warn('BetaWarp encountered negative values: %s' % inputs[inputs<0])

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      1.000000
                width_bucket  float      4.186812
                height_bucke  float      14.999844
Submitted job 9 with local scheduler (process id: 38557).
Status: 1 pending, 8 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.01745 (+/- 0.00122), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490

Minimum of observed values is 0.017442, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      30.000000
                width_bucket  float      1.000000
                height_bucke  float      6.565894
Submitted job 10 with local scheduler (process id: 38564).
Status: 1 pending, 9 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is -0.07341 (+/- 0.14712), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.999268
                vel_bucket_l  float      27.118408
                width_bucket  float      4.302490
                height_bucke  float      9.479980

Minimum of observed values is 0.017442, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      22.916578
                width_bucket  float      4.950625
                height_bucke  float      15.000000
Submitted job 11 with local scheduler (process id: 38571).
Status: 1 pending, 10 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is -0.00066 (+/- 0.25903), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.999207
                vel_bucket_l  float      23.527039
                width_bucket  float      1.370789
                height_bucke  float      13.619995

Minimum of observed values is 0.017442, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      18.563723
                width_bucket  float      10.000000
                height_bucke  float      14.624490
/Users/name/Desktop/external_libraries/Spearmint/spearmint/transformations/beta_warp.py:206: UserWarning: BetaWarp encountered negative values: [ -1.38777878e-17]
  warnings.warn('BetaWarp encountered negative values: %s' % inputs[inputs<0])
/Users/name/Desktop/external_libraries/Spearmint/spearmint/transformations/beta_warp.py:206: UserWarning: BetaWarp encountered negative values: [ -3.46944695e-18]
  warnings.warn('BetaWarp encountered negative values: %s' % inputs[inputs<0])
/Users/name/Desktop/external_libraries/Spearmint/spearmint/transformations/beta_warp.py:206: UserWarning: BetaWarp encountered negative values: [ -1.38777878e-17  -3.46944695e-18]
  warnings.warn('BetaWarp encountered negative values: %s' % inputs[inputs<0])

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      30.000000
                width_bucket  float      1.000000
                height_bucke  float      14.172804
Submitted job 12 with local scheduler (process id: 38578).
Status: 1 pending, 11 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.01177 (+/- 0.00119), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      30.000000
                width_bucket  float      1.000000
                height_bucke  float      14.172804

Minimum of observed values is 0.011719, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      30.000000
                width_bucket  float      1.000000
                height_bucke  float      14.172804

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.996677
                vel_bucket_l  float      30.000000
                width_bucket  float      1.000000
                height_bucke  float      1.000000
Submitted job 13 with local scheduler (process id: 38585).
Status: 1 pending, 12 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.01052 (+/- 0.01036), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.996826
                vel_bucket_l  float      29.539795
                width_bucket  float      1.573486
                height_bucke  float      11.510254

Minimum of observed values is 0.011719, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      30.000000
                width_bucket  float      1.000000
                height_bucke  float      14.172804

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.745479
                vel_bucket_l  float      30.000000
                width_bucket  float      1.000000
                height_bucke  float      15.000000
Submitted job 14 with local scheduler (process id: 38592).
Status: 1 pending, 13 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.01179 (+/- 0.00110), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      30.000000
                width_bucket  float      1.000000
                height_bucke  float      14.172804

Minimum of observed values is 0.011719, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      30.000000
                width_bucket  float      1.000000
                height_bucke  float      14.172804
/Users/name/Desktop/external_libraries/Spearmint/spearmint/transformations/beta_warp.py:206: UserWarning: BetaWarp encountered negative values: [ -8.67361738e-19]
  warnings.warn('BetaWarp encountered negative values: %s' % inputs[inputs<0])

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.916716
                vel_bucket_l  float      30.000000
                width_bucket  float      1.014586
                height_bucke  float      14.696722
Submitted job 15 with local scheduler (process id: 38622).
Status: 1 pending, 14 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.01175 (+/- 0.00106), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      30.000000
                width_bucket  float      1.000000
                height_bucke  float      14.172804

Minimum of observed values is 0.011719, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      30.000000
                width_bucket  float      1.000000
                height_bucke  float      14.172804

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      7.654120
                width_bucket  float      7.379478
                height_bucke  float      14.856693
Submitted job 16 with local scheduler (process id: 38629).
Status: 1 pending, 15 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is -0.04116 (+/- 0.14564), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.999939
                vel_bucket_l  float      27.753845
                width_bucket  float      7.815369
                height_bucke  float      5.153687

Minimum of observed values is 0.008646, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      7.654120
                width_bucket  float      7.379478
                height_bucke  float      14.856693

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.069703
                vel_bucket_l  float      30.000000
                width_bucket  float      1.005543
                height_bucke  float      14.946583
Submitted job 17 with local scheduler (process id: 38637).
Status: 1 pending, 16 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is -0.01464 (+/- 0.14775), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.999939
                vel_bucket_l  float      27.753845
                width_bucket  float      7.815369
                height_bucke  float      5.153687

Minimum of observed values is 0.008646, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      7.654120
                width_bucket  float      7.379478
                height_bucke  float      14.856693

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      29.530498
                width_bucket  float      7.493393
                height_bucke  float      10.860084
Submitted job 18 with local scheduler (process id: 38644).
Status: 1 pending, 17 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.00865 (+/- 0.00103), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      7.654120
                width_bucket  float      7.379478
                height_bucke  float      14.856693

Minimum of observed values is 0.008646, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      7.654120
                width_bucket  float      7.379478
                height_bucke  float      14.856693

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.001565
                vel_bucket_l  float      30.000000
                width_bucket  float      1.000000
                height_bucke  float      1.000000
Submitted job 19 with local scheduler (process id: 38654).
Status: 1 pending, 18 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.00867 (+/- 0.00104), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      7.654120
                width_bucket  float      7.379478
                height_bucke  float      14.856693

Minimum of observed values is 0.008646, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      7.654120
                width_bucket  float      7.379478
                height_bucke  float      14.856693

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.002172
                vel_bucket_l  float      1.000000
                width_bucket  float      10.000000
                height_bucke  float      15.000000
Submitted job 20 with local scheduler (process id: 38686).
Status: 1 pending, 19 complete.

Fitting GP for main task...
Getting suggestion...

Minimum expected objective value under model is 0.00866 (+/- 0.00104), at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      7.654120
                width_bucket  float      7.379478
                height_bucke  float      14.856693

Minimum of observed values is 0.008646, at location:
                NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      1.000000
                vel_bucket_l  float      7.654120
                width_bucket  float      7.379478
                height_bucke  float      14.856693

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                discount      float      0.138561
                vel_bucket_l  float      1.000000
                width_bucket  float      1.000000
                height_bucke  float      1.005832
Submitted job 21 with local scheduler (process id: 38858).
Status: 1 pending, 20 complete.

/Users/name/Desktop/external_libraries/Spearmint/spearmint/tasks/task.py:287: RuntimeWarning: invalid value encountered in subtract
  return y - mean
Fitting GP for main task...
Traceback (most recent call last):
  File "main.py", line 494, in <module>
    main()
  File "main.py", line 286, in main
    suggested_job = get_suggestion(chooser, resource.tasks, db, expt_dir, options, resource_name)
  File "main.py", line 355, in get_suggestion
    hypers = chooser.fit(task_group, hypers, task_options)
  File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/choosers/default_chooser.py", line 309, in fit
    hypers=hypers.get(task_name, None)
  File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/models/gp.py", line 505, in fit
    self._hypers_list = self._collect_samples(self.mcmc_iters)
  File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/models/gp.py", line 378, in _collect_samples
    sampler.sample(self)
  File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/sampling/slice_sampler.py", line 262, in sample
    params_array, current_ll = slice_sample(params_array, self.logprob, model, **self.sampler_options)
  File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/sampling/mcmc.py", line 354, in slice_sample
    new_x, new_llh = direction_slice(direction, init_x)
  File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/sampling/mcmc.py", line 289, in direction_slice
    llh_s = np.log(npr.rand()) + dir_logprob(0.0)
  File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/sampling/mcmc.py", line 272, in dir_logprob
    return logprob(direction*z + init_x, *logprob_args)
  File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/sampling/slice_sampler.py", line 240, in logprob
    lp += model.log_likelihood()
  File "/Users/name/Desktop/external_libraries/Spearmint/spearmint/models/gp.py", line 538, in log_likelihood
    solve = spla.cho_solve((chol, True), self.observed_values - self.mean.value)
  File "/usr/local/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 162, in cho_solve
    b1 = asarray_chkfinite(b)
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 613, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```

**Comment by JasperSnoek** [comment]
I meant the input values and output values for your experiments (not the
code output) :-)

Jasper

**Comment by HansPinckaers** [comment]
I ran into this problem when my own job/experiment function returned nan. (info for future people googling this)

**Comment by cwj006** [comment]
I ran the toy example. It also met this problem. What's wrong?
