### ISSUE TITLE
Incorrect use of local scheduler? (i.e. bad while loop?)

### ISSUE THREAD

**Issue by DanielNScott** [HIPS/Spearmint#60]
On a test problem I've set up to get spearmint working I get the following output:

```
(SPEARMINT_ENV)dscott@rclogin10:/n/moorcroftfs4/dscott/spearmint/spearmint=>python main.py /n/moorcroftfs4/dscott/runfiles/smnt/                                                Using database at localhost.
Getting suggestion...

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                y             float      3.000000
                x             float      0.000000
Submitted job 1 with local scheduler (process id: 32161).
Status: 1 pending, 0 complete.

Getting suggestion...

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                y             float      3.000000
                x             float      0.000000
Submitted job 2 with local scheduler (process id: 32241).
Status: 1 pending, 0 complete.

...

Getting suggestion...

Suggestion:     NAME          TYPE       VALUE
                ----          ----       -----
                y             float      3.000000
                x             float      0.000000
Submitted job 35 with local scheduler (process id: 2208).
Status: 1 pending, 0 complete.

^CTraceback (most recent call last):
  File "main.py", line 494, in <module>
    main()
  File "main.py", line 309, in main
    time.sleep(options.get('polling-time', 5))
KeyboardInterrupt
```

The config file looks like this:
```
  1 {
  2     "language"        : "PYTHON",
  3     "experiment-name" : "smnt-test",
  4     "polling-time"    : 1,
  5     "resources" : {
  6         "my-machine" : {
  7             "scheduler"         : "local",
  8             "max-concurrent"    : 1,
  9             "max-finished-jobs" : 3
 10         }
 11     },
 12     "tasks": {
 13         "job_wrap" : {
 14             "type"       : "OBJECTIVE",
 15             "likelihood" : "NOISELESS",
 16             "main-file"  : "job_wrap",
 17             "resources"  : ["my-machine"]
 18         }
 19     },
 20     "variables": {
 21         "x" : {
 22             "type" : "FLOAT",
 23             "size" : 1,
 24             "min"  : 0,
 25             "max"  : 5
 26         },
 27         "y" : {
 28             "type" : "FLOAT",
 29             "size" : 1,
 30             "min"  : 3,
 31             "max"  : 7
 32         }
 33     }
 34 }
~
~

```

Does anyone know what I might do about this?

**Comment by JasperSnoek** [comment]
Hi @DanielNScott, I think that Spearmint will do this if your script crashes.  I.e. it will just keep suggesting jobs and they'll keep crashing, etc. etc.  The output files in the experiment directory will have the output from your script, which may help with debugging.

**Comment by DanielNScott** [comment]
Thanks, you were exactly right. I had tested the main function and had no problems so I thought it was fine; However, I had tested it assuming the variable "params" being passed into main was a dictionary with keys to floats not keys to lists with floats in them.
