### ISSUE TITLE
Distributed compute nodes not connecting to Mongo

### ISSUE THREAD

**Issue by mikerossgithub** [HIPS/Spearmint#74]
I am trying to run examples/distributed on an Amazon ec2 cluster created with Amazon's cfncluster. Running the simple example (non-distributed) works fine and properly updates the MongoDB. I have also tested SGE with manual calls to qsub, and its working fine. Finally, I made the recommended change to SGE.py to add "-j y" to qsub call. But when I run examples/distributed I get an error in my *.out files which appears to show the compute nodes are trying to connect with the mongo db. Any idea what could be causing this? Is db_address supposed to be setup in examples/distributed/config.json, or is something else going on? 

ERROR:
Traceback (most recent call last):
  File "launcher.py", line 415, in <module>
    main()
  File "launcher.py", line 219, in main
    launch(options.db_address, options.experiment_name, options.job_id)
  File "launcher.py", line 226, in launch
    db  = MongoDB(database_address=db_address)
  File "/shared/git/Spearmint/spearmint/utils/database/mongodb.py", line 202, in __init__
    raise Exception('Could not establish a connection to MongoDB.')
Exception: Could not establish a connection to MongoDB.

**Comment by zh19970205** [comment]
main.py(line 77)  code :
```
db_address = options['database']['address']
db         = MongoDB(database_address=db_address)
```
while options is loads by config.json
so, maybe you can change the config.json:
```
{
    "database"  : {
        "address" : {{ip of the machine with mongod running}}
    }
    ...
}
```
